[package]
name = "data_uri_converter-bin"
version.workspace = true
edition.workspace = true
description = "Convert file to data URI, then output it to stdout"

[[bin]]
name = "data-uri"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true

data_uri_converter = { path = "../lib" }

# CLI argument parsing
clap = { version = "4.5", features = ["derive"] }
