[package]
name = "data-uri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.20.0"
structopt = "0.3.26"
tree_magic_mini = { version = "3.0.3", features = ["tree_magic_db", "with-gpl-data"] }
urlencoding = "2.1.2"
